Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2019
Var
// Seção de Declarações das variáveis 
a, r, d: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- (4.40)
escreva ("Valor em reais: R$")
leia (r)
d <- r*a
escreva ("Em dólar fica: US$",d)
Fimalgoritmo