Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2019
Var
// Seção de Declarações das variáveis 
vendas: real
comissao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Total de vendas num dia: ")
leia (vendas)
comissao <- 0.10 * vendas
escreva ("A sua comissão é: " , comissao)
Fimalgoritmo