Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2019
Var
// Seção de Declarações das variáveis
x, a: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreva ("informe o valor de x")
  leia (x)
  a <- x * 2
  escreva ("o dobro é", a)
Fimalgoritmo
Fimalgoritmo