Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2019
Var
// Seção de Declarações das variáveis 
nome: caractere
idade: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o seu nome: ")
leia (nome)
escreva ("Agora a sua idade: ")
leia (idade)
escreva (nome, idade)

Fimalgoritmo